"""change users table

Revision ID: 6dc2f8e0712b
Revises: 836805d6cf8a
Create Date: 2025-11-12 22:05:04.272554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dc2f8e0712b'
down_revision: Union[str, Sequence[str], None] = '836805d6cf8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This one written manually to include enums
    op.execute("CREATE TYPE diettypeenum AS ENUM ('BALANCED', 'MUSCLE_GAIN', 'ENUDRANCE', 'KETO', 'CUSTOM')")
    op.execute("CREATE TYPE sexenum AS ENUM ('MALE', 'FEMALE')")
    op.execute("CREATE TYPE activitylevelenum AS ENUM ('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'SUPER_ACTIVE')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('diet_type', postgresql.ENUM('BALANCED', 'MUSCLE_GAIN', 'ENUDRANCE', 'KETO', 'CUSTOM', name='diettypeenum'), nullable=True))
    op.add_column('users', sa.Column('macro_split', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # Konwersja istniejących kolumn na ENUM
    op.execute("ALTER TABLE users ALTER COLUMN sex TYPE sexenum USING sex::sexenum")
    op.execute("ALTER TABLE users ALTER COLUMN activity_level TYPE activitylevelenum USING activity_level::activitylevelenum")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activity_level',
               existing_type=postgresql.ENUM('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'SUPER_ACTIVE', name='activitylevelenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='sexenum'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.drop_column('users', 'macro_split')
    op.drop_column('users', 'diet_type')
    # ### end Alembic commands ###
