"""add goals table

Revision ID: 75f461a62b33
Revises: 6dc2f8e0712b
Create Date: 2025-11-16 14:21:35.319075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f461a62b33'
down_revision: Union[str, Sequence[str], None] = '6dc2f8e0712b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_weight', sa.Float(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=False),
    sa.Column('end_weight', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=False),
    sa.Column('is_current', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    # ### end Alembic commands ###
