"""update users table

Revision ID: 836805d6cf8a
Revises: 8794eff2da6e
Create Date: 2025-11-11 13:36:24.845593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836805d6cf8a'
down_revision: Union[str, Sequence[str], None] = '8794eff2da6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'activity_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'activity_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('users', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
