"""add_custom_to_diet_type

Revision ID: 89877b35e0ec
Revises: b517e933e5fc
Create Date: 2026-02-01 22:27:27.015013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89877b35e0ec'
down_revision: Union[str, Sequence[str], None] = 'b517e933e5fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE diettypeenum ADD VALUE 'CUSTOM'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
