"""add remaining tables

Revision ID: c282583e56ee
Revises: 55446eded848
Create Date: 2025-11-25 15:48:22.239306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c282583e56ee'
down_revision: Union[str, Sequence[str], None] = '55446eded848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shortname', sa.String(), nullable=False),
    sa.Column('unit_type', postgresql.ENUM('MASS', 'VOLUME', 'COUNT', name='unittypeenum'), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('base_unit', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('shortname')
    )
    op.create_table('meals',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_kcal', sa.Integer(), nullable=False),
    sa.Column('total_carbs', sa.Float(), nullable=False),
    sa.Column('total_protein', sa.Float(), nullable=False),
    sa.Column('total_fat', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('meal_products',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('meal_uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_uuid', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_short', sa.String(), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_uuid'], ['meals.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_uuid'], ['products.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_products')
    op.drop_table('meals')
    op.drop_table('units')
    # ### end Alembic commands ###
