"""product changes

Revision ID: ca210ea8e74b
Revises: 2e2ad42e0136
Create Date: 2025-12-06 09:27:22.858193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ca210ea8e74b"
down_revision: Union[str, Sequence[str], None] = "2e2ad42e0136"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("meal_products_meal_uuid_fkey"), "meal_products", type_="foreignkey")
    op.drop_column("meal_products", "meal_uuid")

    op.drop_table("meals")

    op.add_column("products", sa.Column("name_from_model", sa.String(), nullable=True))
    op.add_column("products", sa.Column("average_portion", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "average_portion")
    op.drop_column("products", "name_from_model")
    op.add_column("meal_products", sa.Column("meal_uuid", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("meal_products_meal_uuid_fkey"),
        "meal_products",
        "meals",
        ["meal_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_table(
        "meals",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("total_kcal", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("total_carbs", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("total_protein", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("total_fat", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("notes", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("consumed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("last_modified_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("meals_user_id_fkey")),
        sa.PrimaryKeyConstraint("uuid", name=op.f("meals_pkey")),
    )
    # ### end Alembic commands ###
